#!/bin/sh

folder=$HOME/Documents/my_second_brain/

newnote () { \
	name="$(echo "" | dmenu -c -sb "#a3be8c" -nf "#d8dee9" -p "Enter a name: " <&-)"
	setsid -f alacritty -e nvim $folder$name".md" >/dev/null 2>&1
}

selected () { \
	choice=$(echo -e "New\n$(ls -t1 $folder)" | dmenu  -nf "#787878" -sb "#8e8e8e" -c -l 5 -i -p "Choose note or create new: ")
	case $choice in
		New) newnote ;;
		*.md) setsid -f alacritty -e nvim "$folder$choice" >/dev/null 2>&1 ;;
		*) exit ;;
	esac
}

selected

